services:
  - type: web
    name: clearify-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn main:app
